# Generated by Django 5.0.7 on 2024-10-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAgricultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temp_Max', models.FloatField()),
                ('Temp_Min', models.FloatField()),
                ('Humedad', models.FloatField()),
                ('Radiacion_Solar', models.FloatField()),
                ('Viento', models.FloatField()),
                ('Precipitacion', models.FloatField()),
                ('pH_Suelo', models.FloatField()),
                ('Nitrogeno', models.FloatField()),
                ('Fertilizacion', models.FloatField()),
                ('Densidad', models.FloatField()),
                ('N_Flores', models.IntegerField()),
                ('Plagas', models.IntegerField()),
                ('Caida_Frutos', models.FloatField()),
                ('Rendimiento', models.FloatField()),
            ],
        ),
    ]
