# Generated by Django 5.0.7 on 2024-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosagricultura',
            name='Caida_Frutos',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Densidad',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Fertilizacion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Humedad',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Nitrogeno',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Precipitacion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Radiacion_Solar',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Rendimiento',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Temp_Max',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Temp_Min',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='Viento',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='pH_Suelo',
            field=models.CharField(),
        ),
    ]
