# Generated by Django 5.0.7 on 2024-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosagricultura',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datosagricultura',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
