# Generated by Django 5.0.7 on 2024-10-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_datosagricultura_created_datosagricultura_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosagricultura',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datosagricultura',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
