# Generated by Django 5.0.7 on 2024-10-16 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_alter_datosagricultura_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkdatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.datosagricultura')),
                ('pkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.user')),
            ],
        ),
    ]
